title: Yezhaohui Wang's Homepage
page-top-title: Yezhaohui Wang
top-section-bg-text: 迷子でもいい、迷子でも進め
home-subtitle: Yezhaohui Wang&ensp;|&ensp;王叶昭晖
copyright-text: '&copy; Yezhaohui Wang 2023-2025. All Rights Reserved.'
